services:
  - type: web
    name: online-pos
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: "https://github.com/Michael41124436/POS.git"
    branch: main
    autoDeploy: true
